require 'typed_parameter/swagger/types/base'
require 'typed_parameter/swagger/types/integer_type'
require 'typed_parameter/swagger/types/float_type'
require 'typed_parameter/swagger/types/string_type'
require 'typed_parameter/swagger/types/date_type'
require 'typed_parameter/swagger/types/date_time_type'
require 'typed_parameter/swagger/types/boolean_type'
